# Generated by Django 4.1.6 on 2023-07-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
